#%RAML 1.0 NamedExample
{
  "id": 9999999,
  "type_street": "AV",
  "street": "Paulista",
  "number": "1234",
  "complement": "SALA 101",
  "cep": "99999999",
  "ibge": "123321",
  "gia": "1004",
  "district": "Bela vista",
  "state": "São Paulo",
  "city": "São Paulo"
}