#%RAML 1.0 NamedExample
employee:
  {
    "id": 9999999,
    "fistname": "Alexandre",
    "lastname": "Silva",
    "gender": "male",
    "hire_date": "1985-05-01",
    "bank": 
      {
        "name": "Itau",
        "agency": 9999,
        "account": 99999,
        "digit":  9
      },
    "role": 
      {
        "id": 123,
        "role": "Analista"
      },
    "invoice": [{
      "id": 123123123,
      "description": "Car Part Purchase",
      "item": [{
         "id": 1212312,
         "description": "Pneu",
         "amount": 4,
         "value": 150
      }]
    }]
  }