#%RAML 1.0 DataType
type: object
properties: 
  id: 
    type: number
    required: false
  type_street:
    type: string 
    required: false
    enum: 
      - RUA
      - AV 
  street: 
    type: string 
    required: false
  complement: 
    type: string 
    required: false
  number: 
    type: string 
    required: false
  cep: 
    type: string 
    required: false
  ibge: 
    type: string 
    required: false
  gia: 
    type: string 
    required: false
  district: 
    type: string 
    required: false
  state: 
    type: string 
    required: false
  city: 
    type: string 
    required: false