#%RAML 1.0 NamedExample
"legalPerson":
  {
    "id": 9999999,
    "name": "jpl empreendimento",
    "cnpj": "12987789000199",
    "bank": 
      {
        "name": "Itau",
        "agency": 9999,
        "account": 99999,
        "digit":  9
      },
    "address": 
      {
        "id": 9999999,
        "street": "Paulista",
        "number": "1234",
        "cep": "99999999",
        "district": "Bela vista",
        "state": "São Paulo",
        "city": "São Paulo",
      }
  }