#%RAML 1.0 DataType
type: object
properties: 
  id: 
    type: number
    required: false
  type_street:
    type: string 
    required: false
    enum: 
      - RUA
      - AV 
  street: string
  complement: string
  number: string
  cep: string
  ibge: string
  gia: string
  district: string
  state: string
  city: string