#%RAML 1.0 Trait
headers:
  client_id:
    description: The identifier for the user who posts a new organization
    type: string
    example: 9f9167c48btt47609d9e9e521b9fcdb1
  client_secret:
    description: The secret for the user who posts a new organization
    type: string
    example: 38a40f2Ef61c4229b2a00726C248619D